# 5.16 List Dua Dimensi

In [25]:
#################################
# Penggunaan List 2 Dimensi
#################################

# berikut inisialisasi variabel yang memuat list dua dimensi
matrix = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]

# list dua dimensi akan membentuk matriks, dimana '[[ ]]' pertama akan menjadi baris pertama
# walaupun bentuknya tidak sama dengan matriks, namun python mengenalinya sebagai matriks
# maksudnya, python dapat memanggil baris dan kolom yang diperintahkan seperti matriks
print("Berikut adalah matriks intinya : " ,matrix)
print("Akan dipilih baris kedua : " ,matrix[1])
print("Akan dipilih entri (2)(3) : ",matrix[1][2])


#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# berikut adalah hasil syntaxnya
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Berikut adalah matriks intinya :  [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
Akan dipilih baris kedua :  [5, 6, 7, 8]
Akan dipilih entri (2)(3) :  7


In [30]:
# berikut inisialisasi variabel dengan list dua dimensi
beratbadan = [
    [42,45,47,50,52,55,57],
    [60,62,65,67,70,72,75],
    [77,80,82,85,87,90,92],
]
dosis = [
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14],
    [15,16,17,18,19,20,21],
]
print("Diketahui pembagian kelompok berat badan sebagai berikut : ")
print(beratbadan,'\n')
print("Diketahui pembagian kelompok dosis obat sebagi berikut : ")
print(dosis, '\n')

print("Data berat badan pertama akan diurutkan sebagia berikut :")
# fungsi 'for' digunakan untuk mengurutkan data pada index list data beratbadan pertama
for baris1 in beratbadan[0] :
    print(baris1)
# lalu, akan dipanggil index list data dosis pertama
print (" ",dosis[0])
print("Berikut adalah dosis pada data pertama")
print("yang digunakan sesuai urutan terkecil data berat badan")
print('\n')
    
print("Data berat badan kedua akan diurutkan sebagia berikut :")
# fungsi 'for' digunakan untuk mengurutkan data pada index list data beratbadan kedua
for baris2 in beratbadan[1] :
    print (baris2 )
# lalu, akan dipanggil index list data dosis kedua
print (" ",dosis[1])
print("Berikut adalah dosis pada data kedua")
print("yang digunakan sesuai urutan terkecil data berat badan")
print('\n')

print("Data berat badan ketiga akan diurutkan sebagia berikut :")
# fungsi 'for' digunakan untuk mengurutkan data pada index list data beratbadan ketiga
for baris3 in beratbadan[2] :
    print (baris3)
# lalu, akan dipanggil index list data dosis ketiga
print("Berikut adalah dosis pada data ketiga")
print("yang digunakan sesuai urutan terkecil data berat badan")    
print (" ",dosis[2])


#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# berikut adalah hasil syntaxnya
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Diketahui pembagian kelompok berat badan sebagai berikut : 
[[42, 45, 47, 50, 52, 55, 57], [60, 62, 65, 67, 70, 72, 75], [77, 80, 82, 85, 87, 90, 92]] 

Diketahui pembagian kelompok dosis obat sebagi berikut : 
[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14], [15, 16, 17, 18, 19, 20, 21]] 

Data berat badan pertama akan diurutkan sebagia berikut :
42
45
47
50
52
55
57
  [1, 2, 3, 4, 5, 6, 7]
Berikut adalah dosis pada data pertama
yang digunakan sesuai urutan terkecil data berat badan


Data berat badan kedua akan diurutkan sebagia berikut :
60
62
65
67
70
72
75
  [8, 9, 10, 11, 12, 13, 14]
Berikut adalah dosis pada data kedua
yang digunakan sesuai urutan terkecil data berat badan


Data berat badan ketiga akan diurutkan sebagia berikut :
77
80
82
85
87
90
92
Berikut adalah dosis pada data ketiga
yang digunakan sesuai urutan terkecil data berat badan
  [15, 16, 17, 18, 19, 20, 21]


# 

# 5.17 Tuples

In [24]:
#################################
# Penggunaan Tuples
#################################

# berikut inisialisasi variabel menggunakan fungsi tuples
# pada fungsi tuples, data tidak dapat dirubah seperti fungsi list
bilganjil = (1,3,5,7,7,9,11)
print("Diketahui deret bilangan ganjil (1,3,5,7,9,11)")

# berikut akan dicari suku pertama dari data tuples dengan mencantumkan indexnya pada variabel
print("Berikut adalah suku pertama deret bilangan ganjil : " , bilganjil[0])

# berikut akan diketahui semua data tuples dengan mencantumkan indexnya pada variabel
print("Berikut adalah seluruh deret bilangan ganjil : ", bilganjil[0:7])

# berikut akan dicari urutan dari 2 suku pertama pada data tuples 
# dengan menggunakan for sebagai fungsi yang mengurutkan kebawah
# lalu memasukan variabel sebarang pada variabel tuples
print("Berikut adalah urutan dari 2 angka awal pada deret : ")
for urutan in bilganjil[0:2]:
    print(urutan)

# berikut akan diketahui banyaknya suku bilangan 7 pada data tuples dengan fungsi 'count'
print("\nMisal ditanyakan ada berapa banyak bilangan 7 pada deret bilangan ganjil")
print("Maka, akan diketahui:" , bilganjil.count(7))


# berikut akan diketahui urutan bilangan 5 pada data tuples dengan fungsi 'index'
print("\n\nMisal ditanyakan pada urutan keberapa bilangan 5 pada deret bilangan ganjil")
print("Maka, akan diketahui:" , bilganjil.index(5))


#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# berikut adalah hasil syntaxnya
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Diketahui deret bilangan ganjil (1,3,5,7,9,11)
Berikut adalah suku pertama deret bilangan ganjil :  1
Berikut adalah seluruh deret bilangan ganjil :  (1, 3, 5, 7, 7, 9, 11)
Berikut adalah urutan dari 2 angka awal pada deret : 
1
3

Misal ditanyakan ada berapa banyak bilangan 7 pada deret bilangan ganjil
Maka, akan diketahui: 2


Misal ditanyakan pada urutan keberapa bilangan 5 pada deret bilangan ganjil
Maka, akan diketahui: 2


# 

# 5.18 Dictionaries

In [23]:
#################################
# Penggunaan Dictionaries
#################################

# berikut inisialisasi data dictionaries dengan data string
data_orang ={
    "nama" : "Leonardo",
    "umur" : "17",
    "apakah mahasiswa" : True
}

# data dictionaries yang dipanggil memerlukan '[ ]' untuk memasukan data string nya
print('nama : ', data_orang['nama'])
print('umur : ', data_orang['umur'])
print('apakah mahasiswa : ', data_orang['apakah mahasiswa'], '\n')

# data dictionaries yang dipanggil dapat menggunakan fungsi 'get' untuk memperjelas memanggilannya
print("Apakah Leonardo seorang mahasiswa?:", data_orang.get('apakah mahasiswa'))
print("Jika Leonardo adalah mahasiswa Universitas Udayana,")
print("Maka sesuai data diatas, kira-kira umur Leonardo adalah : " , data_orang.get('umur'))


#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# berikut adalah hasil syntaxnya
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

nama :  Leonardo
umur :  17
apakah mahasiswa :  True 

Apakah Leonardo seorang mahasiswa?: True
Jika Leonardo adalah mahasiswa Universitas Udayana,
Maka sesuai data diatas, kira-kira umur Leonardo adalah :  17


# 

# 5.19 Fungsi dalam Python

In [22]:
#################################
# Penggunaan Fungsi
#################################


# berikut inisialisasi fungsi 'waktu_sampai' yang memerlukan 2 variabel
# variabel tersebut adalah 'jarak' & 'tinggi'
def waktu_sampai(jarak, kecepatan):
    # berikut adalah operasi fungsinya
    waktu = jarak/kecepatan
    # diperlukan operator 'return' untuk memanggil kembali variabel operasi fungsinya
    return waktu

# variabel a memanggil fungsi 'waktu_sampai'
# dengan jarak = 100 dan kecepatan = 60
a = waktu_sampai(100,60)
print("Jika diketahui jarak tempuh mobil adalah 100 km dan kecepatan mobil adalah 60km/jam")
print("Maka diketahui mobil akan sampai tujuan setelah " , a , "jam")



# berikut inisialisasi fungsi 'luas_segitiga' yang memerlukan 2 variabel
# variabel tersebut adalah 'alas' & 'tinggi'
def luas_segitiga(alas,tinggi) :
    # berikut adalah operasi fungsinya
    luas = (1/2) * alas * tinggi
    # diperlukan operator 'return' untuk memanggil kembali variabel operasi fungsinya
    return luas

# variabel b memanggil fungsi 'luas_segitiga'
# dengan alas = 5 dan tinggi = 10
b = luas_segitiga(5,10)
print("\nJika diketahui sebuah segitiga dengan alas = 5 cm dan tinggi = 10 cm")
print("Maka diketahui luas segitiganya adalah " ,b)



# berikut inisialisasi fungsi 'deret_aritmatika' yang memerlukan 3 variabel
# variabel tersebut adalah 'sukuawal', 'banyaksuku', dan 'beda'
def deret_aritmatika(sukuawal,banyaksuku,beda):
    # berikut adalah operasi fungsinya
    deret = (banyaksuku/2)*((2*sukuawal) + (banyaksuku-1)*beda) 
    # diperlukan operator 'return' untuk memanggil kembali variabel operasi fungsinya
    return deret

# variabel c memanggil fungsi 'deret_aritmatika'
# dengan sukuawal = 3 , banyaksuku = 9 , dan beda = 2
c = deret_aritmatika(3,9,2) 
print("\nJika diketahui sebuah deret dengan suku awal = 3, banyak suku = 9, dan beda antarsuku = 2")
print("Jumlah deretnya adalah : ", c)
        
# berikut inisialisasi fungsi 'deret_geometri' dengan 3 variabel
# variabel tersebut adalah 'sukuawal', 'rasio', dan 'banyaksuku'
def deret_geometri (sukuawal,rasio,banyaksuku) :
    # fungsi terbagi menjadi 2 dengan fungsi 'if' & 'elif'
    if rasio < 1:
        # pada fungsi 'if' , variabel 'rasio' harus kurang dari 1
        # berikut adalah operasi fungsinya
        deretgeoturun = sukuawal * ((1 - rasio**banyaksuku)/(1-rasio))
        # diperlukan operator 'return' untuk memanggil kembali variabel operasi fungsinya
        return deretgeoturun
    
    elif rasio > 1:
        # pada fungsi 'elif' , variabel 'rasio' harus lebih dari 1
        # berikut adalah operasi fungsinya
        deretgeonaik = sukuawal * ((rasio**banyaksuku - 1)/(rasio - 1))
        # diperlukan operator 'return' untuk memanggil kembali variabel operasi fungsinya
        return deretgeonaik
    

sukuawal_31 = int(input("\nMasukkan suku awal deret geometrinya : "))
banyaksuku_31 = int(input("Masukkan banyak suku deret geometrinya : "))
rasio_31 = int(input("Masukkan rasio antarsukunya : "))

# variabel d memanggil fungsi 'deret_geometri'
# dengan sukuawal = sukuawal_31 , rasio = rasio_31 , dan banyaksuku = banyaksuku_31
d = deret_geometri(sukuawal_31,rasio_31,banyaksuku_31)
print("\nJika diketahui sebuah deret dengan suku awal = ", sukuawal_31 , " banyak suku = ", banyaksuku_31, "dan rasio antarsuku = ", rasio_31)
print("Jumlah deretnya adalah : ", d)


#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# berikut adalah hasil syntaxnya
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Jika diketahui jarak tempuh mobil adalah 100 km dan kecepatan mobil adalah 60km/jam
Maka diketahui mobil akan sampai tujuan setelah  1.6666666666666667 jam

Jika diketahui sebuah segitiga dengan alas = 5 cm dan tinggi = 10 cm
Maka diketahui luas segitiganya adalah  25.0

Jika diketahui sebuah deret dengan suku awal = 3, banyak suku = 9, dan beda antarsuku = 2
Jumlah deretnya adalah :  99.0

Masukkan suku awal deret geometrinya : 1
Masukkan banyak suku deret geometrinya : 10
Masukkan rasio antarsukunya : 2

Jika diketahui sebuah deret dengan suku awal =  1  banyak suku =  10 dan rasio antarsuku =  2
Jumlah deretnya adalah :  1023.0


# 

# 5.20 Numpy

## 5.20.1 Perintah dasar pada numpy

In [21]:
# inisialisasi numpy sebagai np
import numpy as np

# inisialisasi variabel dengan fungsi array pada numpy(np)
a = np.array([1,2,3,4])
# hasil dari inisialisasi variabel a
print("Diketahui data array(a) sebagai berikut : ",a)
print('\n')

# inisialisasi variabel dengan fungsi array pada numpy(np)
# numpy akan memdeskripsikan array sebagai matriks
b = np.array([[5,6,7,8],
              [9,8,7,6]])
# hasil dari inisialisasi variabel b
print("Diketahui data array(b) yang memiliki 2 buah baris sebagai berikut : ",b)
print('\n')


# inisialisai variabel dengan fungsi array pada numpy(np)
# numpy akan meninisialisasi data di dalam "[]" sebagai baris
# dan data didalam "[[ ]]" sebagai kolom
c = np.array([
    [1,2,3,4],[5,6,7,8],
    [9,10,11,12],[13,14,15,16],
    [17,18,19,20],[21,22,23,24]
])
# hasil dari inisialisasi variabel c
print("Diketahui data array(c) yang memiliki beberapa baris sebagia berikut : ",c)
print('\n')

# fungsi 'ndim' digunakan untuk menghitung banyaknya baris numpy
# fungsi 'shape' digunakan untuk menghitung ordo numpy
x = a.ndim
y = a.shape
print("Berikut adalah banyaknya baris yang dimiliki data array(a) : ",x, "dan ordo pada data array(a) : ",y)

x1 = b.ndim
y1 = b.shape
print("Berikut adalah banyaknya baris yang dimiliki data array(b) : ",x1, "dan ordo pada data array(b) : ",y1)

x2 = c.ndim
y2 = c.shape
print("Berikut adalah banyaknya baris yang dimiliki data array(c) : ",x2, "dan ordo pada data array(c) : ",y2)


#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# berikut adalah syntaxnya
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Diketahui data array(a) sebagai berikut :  [1 2 3 4]


Diketahui data array(b) yang memiliki 2 buah baris sebagai berikut :  [[5 6 7 8]
 [9 8 7 6]]


Diketahui data array(c) yang memiliki beberapa baris sebagia berikut :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


Berikut adalah banyaknya baris yang dimiliki data array(a) :  1 dan ordo pada data array(a) :  (4,)
Berikut adalah banyaknya baris yang dimiliki data array(b) :  2 dan ordo pada data array(b) :  (2, 4)
Berikut adalah banyaknya baris yang dimiliki data array(c) :  2 dan ordo pada data array(c) :  (6, 4)


# 

## 5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

In [17]:
import numpy as np

# berikut inisialisasi variabel dengan fungsi array pada numpy(np)
d = np.array([
    [1,2,3,4],[5,6,7,8],[9,10,11,12]
])
print("Diketahui data array sebagai berikut : ")
# hasilnya akan berupa matrik dengan barisnya adalah banyaknya index array
# dan kolom adalah index pada list data
print(d)
print('\n')

# berikut inisialisasi variabel dengan penjumlahan index array yang bertipe data integer
z = int(d[0,3]) + int(d[2,1])
print("Akan dicari hasil penjumlahan dari baris pertama kolom ke 4 dan baris ketiga kolom ke 2 data diatas : ",z)
print('\n')

# berikut inisialisasi variabel dengan mencari seluruh index data array pada data array pertama
f = d[0,:]
print("Akan diurutkan seluruh data dari baris pertama data : ",f)
print('\n')

# berikut inisialisari variabel dengan mencari index data array pertama pada seluruh data array
f2 = d[:,0]
print("Akan diurutkan data pertama pada seluruh baris : ",f2)
print('\n')

# berikut inisialisasi variabel dengan mencari index 1:2 pada data array pertama
f3 = d[0,1:2]
print("Akan dicari data array kedua pada baris pertama : ",f3)
print('\n')

# berikut inisialisasi variabel dengan mecari index 0:3:1 pada data array kedua
f4 = d[2, 0:3:1]
print("Akan dicari data array pertama sampai ketiga pada baris ketiga : ",f4)
print('\n')

# berikut inisialisasi variabel mengganti index 1 pada data array pertama
d[0,1] = 200
print("Akan digantik data array kedua pada baris pertama dengan '200' : ",d)


#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# berikut adalah syntaxnya
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Diketahui data array sebagai berikut : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Akan dicari hasil penjumlahan dari baris pertama kolom ke 4 dan baris ketiga kolom ke 2 data diatas :  14


Akan diurutkan seluruh data dari baris pertama data :  [1 2 3 4]


Akan diurutkan data pertama pada seluruh baris :  [1 5 9]


Akan dicari data array kedua pada baris pertama :  [2]


Akan dicari data array pertama sampai ketiga pada baris ketiga :  [ 9 10 11]


Akan digantik data array kedua pada baris pertama dengan '200' :  [[  1 200   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


# 

## 5.20.3 Matrix pada Numpy

In [14]:
import numpy as np

# berikut inisialisasi variabel dengan fungsi 'ones(( ))' 
# 'ones(( ))' digunakan untuk membentuk entri '1.' pada seluruh entri array
# dengan '(( ))' digunakan untuk ordo array tersebut
x = np.ones((2,3))
print("Akan dibentuk data array dengan ordo 2x3 yang memiliki seluruh entri '1.' : ",x)
print('\n')

# berikut inisialisasi variabel dengan fungsi 'zeros(( ))'
# 'zeros(( ))' digunakan untuk membentuk entri '0.' pada seluruh entri array
# dengan '(( ))' digunakan untuk ordo array tersebut
x1 = np.zeros((3,2))
print("Akan dibentuk data array dengan ordo 3x2 yang memiliki seluruh entri '0.' : ",x1)
print('\n')

# berikut inisialisasi variabel dengan fungsi 'identity()'
# 'identity()' digunakan untuk membentuk matriks identitas
# dengan '()' digunakan sebagai ordo array
# karena matriks identitas adalah matrik bujursangkar, maka hanya perlu 1 ordo
x2 = np.identity(4)
print("Akan dibentuk data array dengan ordo 4x4 yang merupakan matriks identitas : ",x2)
print('\n')

# berikut inisialisasi variabel dengan fungsi 'ones(( , , , ))'
# 'ones(( , , , ))' digunakan untuk membentuk entri '1.' pada seluruh entri array
# dengan '(( , , , ))' digunakan untuk membentuk berapa array, baris array, dan kolom array
x3 = np.ones((2,3,4))
print("Akan dibentuk 2 data array dengan ordo 3x4 yang memiliki seluruh entri '1.' : ", x3)
print('\n')

# berikut inisialisasi variabel dengan fungsi 'full(( , ), )'
# 'full(( , ), )' digunakan untuk membentuk data array dengan satu bentuk entri pada seluruh data
# dengan '(( , ), )' digunakan untuk membentuk ordo array dan data array yang ingin dibentuk
x4 = np.full((3,2),9)
print("Akan dibentuk data array dengan ordo 3x2 yang memiliki seluruh entri '9' : ", x4)
print('\n')

# berikut inisialisasi variabel dengan fungsi 'random.rand( , )'
# 'random.rand( , )' digunakan untuk membentuk data array yang berisi entri dengan nilai random
# dengan '( , )' digunakan untuk membentuk ordo array
x5 = np.random.rand(4,3)
print("Akan dibentuk data array dengan ordo 4x3 yang memiliki seluruh entri random : ",x5)
print('\n')

# berikut inisialisasi variabel dengan fungsi 'random.randint( , ,size = ( , ))'
# 'random.randint( , ,size = ( , ))' digunakan untuk membentuk data array yang berisi entri dengan nilai random
# namun, nilai random disini memiliki batas, dengan '( , ,size...)' sebagai batasnya
# dan 'size = ( , )' digunakan untuk membentuk ordo array
x6 = np.random.randint(1,10,size = (3,4))
print("Akan dibentuk data array dengan ordo 3x4 yang memiliki seluruh entri random dari 1-10 : ",x6)

#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# berikut adalah syntaxnya
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Akan dibentuk data array dengan ordo 2x3 yang memiliki seluruh entri '1.' :  [[1. 1. 1.]
 [1. 1. 1.]]


Akan dibentuk data array dengan ordo 3x2 yang memiliki seluruh entri '0.' :  [[0. 0.]
 [0. 0.]
 [0. 0.]]


Akan dibentuk data array dengan ordo 4x4 yang merupakan matriks identitas :  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Akan dibentuk 2 data array dengan ordo 3x4 yang memiliki seluruh entri '1.' :  [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Akan dibentuk data array dengan ordo 3x2 yang memiliki seluruh entri '9' :  [[9 9]
 [9 9]
 [9 9]]


Akan dibentuk data array dengan ordo 4x3 yang memiliki seluruh entri random :  [[0.26164246 0.22155274 0.71001016]
 [0.72028285 0.79873573 0.79687985]
 [0.0068325  0.85923024 0.68578274]
 [0.63301735 0.22543353 0.28495881]]


Akan dibentuk data array dengan ordo 3x4 yang memiliki seluruh entri random dari 1-10 :  [[6 8 8 6]
 [6 7 3 6]
 [5 1 6 3]]


# 

## 5.20.4 Copy pada Numpy

In [11]:
import numpy as np

# berikut inisialisasi variabel dengan fungsi array pada numpy(np)
a = np.array([1,2,3,4,5])
print("Diketahui data array(a) sebagai berikut : " ,a)
# variabel akan di 'copy' dengan fungsi 'copy()'
b = a.copy()
# berikut adalh hasil copy variabel
print("Data tersebut akan dicopy pada array(b) seperti berikut : ",b)

# berikut inisialisasi variabel dengan fungsi array pada numpy(np)
c = np.array([6,7,8,9])
print("\nDiketahui data array(c) sebagai berikut : ",c)
# variabel akan di 'copy' dengan fungsi 'copy()'
d = c.copy()
# berikut adalah hasil copy variabel
print("Data tersebut akan dicopy pada array(d)  seperti berikut : ",d)


print("Sehingga kedua array copy tersebut indentik dengan array originalnya : \n",b ,d)


#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# berikut adalah syntaxnya
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Diketahui data array(a) sebagai berikut :  [1 2 3 4 5]
Data tersebut akan dicopy pada array(b) seperti berikut :  [1 2 3 4 5]

Diketahui data array(c) sebagai berikut :  [6 7 8 9]
Data tersebut akan dicopy pada array(d)  seperti berikut :  [6 7 8 9]
Sehingga kedua array copy tersebut indentik dengan array originalnya : 
 [1 2 3 4 5] [6 7 8 9]


# 

## 5.20.5 Operasi Matematika pada Numpy

In [3]:
import numpy as np

# berikut inisialisasi variabel dengan fungsi array pada numpy
a = np.array([1,2,3,4,5])
print("Diketahui data array [1,2,3,4,5] \n")
b = np.array([6,7,8,9,10])

# berikut inisialisasi variabel dengan operasi '+' pada variabel 'a'
# operasi '+' adalah operasi penjumlahan
x1 = a+1

# berikut inisialisasi variabel dengan operasi '-' pada variabel 'a'
# operasi '-' adalah operasi pengurangan
x2 = a-1

# berikut inisialisasi variabel dengan operasi '*' pada variabel 'a'
# operasi '*' adalah operasi perkalian
x3 = a*2

# berikut inisialisasi variabel dengan operasi '/' pada variabel 'a'
# operasi '/' adalah operasi pembagian
x4 = a/2

# berikut inisialisasi variabel dengan operasi '**' pada variabel 'a'
# operasi '**' adalah operasi pemangkatan
x5 = a**b
print("Nilai a+1 : " , x1,'\n')
print("Nilai a-1 : ", x2,'\n')
print("Nilai ax1 : ", x3,'\n')
print("Nilai a/1 : ", x4,'\n')
print("Nilai a pangkat b : ", x5,'\n')


# berikut inisialisasi variabel dengan operasi 'cos()' pada variabel 'a'
# operasi 'cos()' adalah operasi pembentukan nilai cos dari data pada '()'
y1 = np.cos(a)

# berikut inisialisasi variabel dengan operasi 'sin()' pada variabel 'a'
# operasi 'sin()' adalah operasi pembentukan nilai sin dari data pada '()'
y2 = np.sin(a)

# berikut inisialisasi variabel dengan operasi 'tan()' pada variabel 'a'
# operasi 'tan()' adalah operasi pembentukan nilai tan dari data pada '()'
y3 = np.tan(a)

# berikut inisialisasi variabel dengan operasi 'sinh()' pada variabel 'a'
# operasi 'sinh()' adalah operasi pembentukan nilai sin hiperbolik dari data pada '()'
y4 = np.sinh(a)

# berikut inisialisasi variabel dengan operasi 'cosh()' pada variabel 'a'
# operasi 'cosh()' adalah operasi pembentukan nilai cos hiperbolik dari data pada '()'
y5 = np.cosh(a)

# berikut inisialisasi variabel dengan operasi 'tanh()' pada variabel 'a'
# operasi 'tanh()' adalah operasi pembentukan nilai tan hiperbolik dari data pada '()'
y6 = np.tanh(a)

# berikut inisialisasi variabel dengan operasi 'sqrt()' pada variabel 'a'
# operasi 'sqrt()' adalah operasi yang mencari nilai akar kuadrat dari data '()'
y7 = np.sqrt(a)
print("Nilai cos(a) : ", y1,'\n')
print("Nilai sin(a) : ",y2,'\n')
print("Nilai tan(a) : ",y3,'\n')
print("Nilai cosh(a) : ",y4,'\n')
print("Nilai sinh(a) : ",y5,'\n')
print("Nilai tanh(a) : ",y6,'\n')
print("Nilai akar kuadrat a : ",y7,'\n')

#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# berikut adalah syntaxnya
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Diketahui data array [1,2,3,4,5] 

Nilai a+1 :  [2 3 4 5 6] 

Nilai a-1 :  [0 1 2 3 4] 

Nilai ax1 :  [ 2  4  6  8 10] 

Nilai a/1 :  [0.5 1.  1.5 2.  2.5] 

Nilai a pangkat b :  [      1     128    6561  262144 9765625] 

Nilai cos(a) :  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219] 

Nilai sin(a) :  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427] 

Nilai tan(a) :  [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501] 

Nilai cosh(a) :  [ 1.17520119  3.62686041 10.01787493 27.2899172  74.20321058] 

Nilai sinh(a) :  [ 1.54308063  3.76219569 10.067662   27.30823284 74.20994852] 

Nilai tanh(a) :  [0.76159416 0.96402758 0.99505475 0.9993293  0.9999092 ] 

Nilai akar kuadrat a :  [1.         1.41421356 1.73205081 2.         2.23606798] 



# 

## 5.20.6 Perkalian Matrik pada Numpy 

In [6]:
import numpy as np

# berikut inisialisasi variabel dengan fungsi array pada numpy(np)
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[9,10,11,12],[13,14,15,16]])
print("Diketahui data array : ")
print(a)
print(b)
      
# variabel sebelumnya akan dioperasikan dengan '*' pada sebuah variabel baru
# ini adalah bentuk perkalian masing-masing entri pada variabel fungsi array      
c = a*b
print("\nNilai dari a*b : ", c)      

# berikut inisialisasi variabel dengan fungsi array pada numpy(np)
e = np.array([[9,10], [11,12],[13,14],[15,16]])
      
print("\nDiketahui juga data array kedua : ")
print('\n')
print(e)

# variabel 'a' dan 'e' akan operasikan dengan fungsi 'matmul()' 
# fungsi 'matmul()' berfungsi untuk mengalikan kedua matriks
f = np.matmul(a,e)
print(f)
print("\nJika array 'a' dan 'e' diketahui sebagai matriks,")
print("Maka hasil kalinya adalah : ")
print(f)

#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# berikut adalah syntaxnya
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Diketahui data array : 
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]

Nilai dari a*b :  [[  9  20  33  48]
 [ 65  84 105 128]]

Diketahui juga data array kedua : 


[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]
[[130 140]
 [322 348]]

Jika array 'a' dan 'e' diketahui sebagai matriks,
Maka hasil kalinya adalah : 
[[130 140]
 [322 348]]


# 

## 5.20.7 min, max dan sum pada Numpy

In [9]:
import numpy as np

# berikut inisialisasi variabel dengan fungsi array pada numpy(np)
# dengan 3 baris dan 4 kolom
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
print("Diketahui data array : ")
print(a)
print('\n')

# berikut adalah fungsi 'min()' pada data 'a'
# 'min()' digunakan untuk mencari nilai minimum data array
print("Nilai minimum dari data array tersebut adalah : ")
b = np.min(a)
print(b,'\n')

# berikut adalah fungsi 'min( , axis=0)' pada data 'a'
# 'min( , axis=0)' digunakan untuk mencari data minimum pada baris data array
# dengan axis = 0 menujukan 'baris' data array
c = np.min(a,axis=0)
print("Data minimum baris data arrray tersebut adalah : " ,c,'\n')

# berikut adalah fungsi 'min( , axis=1)' pada data 'a'
# 'min( , axis=1)' digunakan untuk mencari data minimum pada kolom data array
# dengan axis = 1 menujukan 'kolom' data array
d = np.min(a,axis=1)
print("Data minimum kolom data array tersebut adalah : " ,d,'\n')

# berikut adalah fungsi 'max()' pada data 'a'
# 'max()' digunakan untuk mencari nilai maksimum data array
e = np.max(a)
print("Nilai maksimum dari data array tersebut adalah : " ,e,'\n')

# berikut adalah fungsi 'max( , axis=0)' pada data 'a'
# 'max( , axis=0)' digunakan untuk mencari data maksimum pada baris data array
# dengan axis = 0 menujukan 'baris' data array
f = np.max(a,axis=0)
print("Data maksimum baris data array tersebut adalah : " ,f,'\n')

# berikut adalah fungsi 'max( , axis=1)' pada data 'a'
# 'max( , axis=1)' digunakan untuk mencari data maksimum pada kolom data array
# dengan axis = 1 menujukan 'kolom' data array
g = np.max(a,axis=1)
print("Data maksimum kolom data array tersebut adalah : " ,g,'\n')

# berikut adalah fungsi 'sum()' pada data 'a'
# 'sum()' digunakan untuk menjumlah seluruh data array
h = np.sum(a)
print("Jumlah data array tersebut adalah : " ,h,'\n')

# berikut adalah fungsi 'sum( , axis=0)' pada data 'a'
# 'sum( , axis=0)' digunakan untuk menjumlah data pada baris data array
# dengan axis = 0 menunjukan 'baris' data array
h2 = np.sum(a,axis=0)
print("Jumlah data baris array tersebut adalah : " ,h2,'\n')

# berikut adalah fungsi 'sum( , axis=1)' pada data 'a'
# 'sum( , axis=1)' digunakan untuk menjumlah data pada kolom data array
# dengan axis = 1 menunjukan 'kolom' data array
h3 = np.sum(a,axis=1)
print("Jumlah data kolom array tersebut adalah : " ,h3,'\n')

#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# berikut adalah syntaxnya
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

Diketahui data array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Nilai minimum dari data array tersebut adalah : 
1 

Data minimum baris data arrray tersebut adalah :  [1 2 3 4] 

Data minimum kolom data array tersebut adalah :  [1 5 9] 

Nilai maksimum dari data array tersebut adalah :  12 

Data maksimum baris data array tersebut adalah :  [ 9 10 11 12] 

Data maksimum kolom data array tersebut adalah :  [ 4  8 12] 

Jumlah data array tersebut adalah :  78 

Jumlah data baris array tersebut adalah :  [15 18 21 24] 

Jumlah data kolom array tersebut adalah :  [10 26 42] 

